In [1]:
import numpy as np
import pandas as pd

docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='nothing')

In [3]:
tokenizer.fit_on_texts(docs)

In [4]:
tokenizer.word_index

{'nothing': 1,
 'india': 2,
 'jeetega': 3,
 'hip': 4,
 'ki': 5,
 'jai': 6,
 'kohli': 7,
 'sachin': 8,
 'dhoni': 9,
 'go': 10,
 'hurray': 11,
 'bhai': 12,
 'bharat': 13,
 'mata': 14,
 'modi': 15,
 'ji': 16,
 'inquilab': 17,
 'zindabad': 18}

In [5]:
tokenizer.word_counts

OrderedDict([('go', 1),
             ('india', 4),
             ('hip', 2),
             ('hurray', 1),
             ('jeetega', 3),
             ('bhai', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 2),
             ('jai', 2),
             ('kohli', 2),
             ('sachin', 2),
             ('dhoni', 2),
             ('modi', 1),
             ('ji', 1),
             ('inquilab', 1),
             ('zindabad', 1)])

In [6]:
tokenizer.document_count
# no of sentences

10

In [7]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[10, 2],
 [2, 2],
 [4, 4, 11],
 [3, 12, 3, 2, 3],
 [13, 14, 5, 6],
 [7, 7],
 [8, 8],
 [9, 9],
 [15, 16, 5, 6],
 [17, 18]]

In [22]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[10,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 4,  4, 11,  0,  0],
       [ 3, 12,  3,  2,  3],
       [13, 14,  5,  6,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [ 9,  9,  0,  0,  0],
       [15, 16,  5,  6,  0],
       [17, 18,  0,  0,  0]], dtype=int32)

In [24]:
print(sequences)
print(np.max(sequences))
# finding valid no of vocab count -1 to put in embedding layer

[[10  2  0  0  0]
 [ 2  2  0  0  0]
 [ 4  4 11  0  0]
 [ 3 12  3  2  3]
 [13 14  5  6  0]
 [ 7  7  0  0  0]
 [ 8  8  0  0  0]
 [ 9  9  0  0  0]
 [15 16  5  6  0]
 [17 18  0  0  0]]
18


In [18]:
# embeddings
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Embedding,Dense
model2 = Sequential()
model2.add(Embedding(19,output_dim=2))

In [19]:
model2.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [20]:
model2.compile('adam','accuracy')

In [21]:
pred = model2.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step
[[[-0.04871649  0.0199053 ]
  [-0.0029188  -0.00696809]
  [-0.03489993  0.01417173]
  [-0.03489993  0.01417173]
  [-0.03489993  0.01417173]]

 [[-0.0029188  -0.00696809]
  [-0.0029188  -0.00696809]
  [-0.03489993  0.01417173]
  [-0.03489993  0.01417173]
  [-0.03489993  0.01417173]]

 [[ 0.04028876 -0.01327185]
  [ 0.04028876 -0.01327185]
  [ 0.02552025  0.01950533]
  [-0.03489993  0.01417173]
  [-0.03489993  0.01417173]]

 [[-0.04653618 -0.00296716]
  [ 0.00014367  0.0428861 ]
  [-0.04653618 -0.00296716]
  [-0.0029188  -0.00696809]
  [-0.04653618 -0.00296716]]

 [[ 0.03065841  0.03525234]
  [-0.01917081 -0.02487382]
  [-0.04928377 -0.03988769]
  [ 0.02890452  0.0153042 ]
  [-0.03489993  0.01417173]]

 [[-0.03352433  0.00810283]
  [-0.03352433  0.00810283]
  [-0.03489993  0.01417173]
  [-0.03489993  0.01417173]
  [-0.03489993  0.01417173]]

 [[ 0.02715873 -0.03697412]
  [ 0.02715873 -0.03697412]
  [-0.03489993  0.01417173]
  [-0.03489993  0.01417173